# Generated by Django 3.1.7 on 2021-06-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='DateofJoining',
            new_name='DateOfJoining',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeNmae',
            new_name='EmployeeName',
        ),
    ]
